version: '3.8'

services:
  todo-restapi:
    networks:
      - new
    build: ./
    command: ./todo-restapi
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    networks:
      new:
        aliases:
          - database
    volumes:
    - ./.database/postgres/data:/var/lib/postgrsql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_DB}
      - POSTGRES_PASSWORD:${POSTGRES_DB}
    ports:
    - "5432"

  migrate:
    image:  migrate/migrate
    networks:
      - new
    volumes:
    - ./schema:/migrations
    env_file:
      - .env
    command: [ "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    links:
      - postgres
    depends_on:
      - todo-restapi
networks:
  new: